
package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BoxOfficeAPIService", targetNamespace = "http://www.kobis.or.kr/kobisopenapi")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BoxOfficeAPIService {


    /**
     * 
     * @param weekGb
     * @param multiMovieYn
     * @param wideAreaCd
     * @param repNationCd
     * @param itemPerPage
     * @param targetDt
     * @param key
     * @return
     *     returns wsdl.WeeklyBoxOfficeResult
     * @throws OpenAPIFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchWeeklyBoxOfficeList", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "wsdl.SearchWeeklyBoxOfficeList")
    @ResponseWrapper(localName = "searchWeeklyBoxOfficeListResponse", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "wsdl.SearchWeeklyBoxOfficeListResponse")
    public WeeklyBoxOfficeResult searchWeeklyBoxOfficeList(
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "targetDt", targetNamespace = "")
        String targetDt,
        @WebParam(name = "itemPerPage", targetNamespace = "")
        String itemPerPage,
        @WebParam(name = "weekGb", targetNamespace = "")
        String weekGb,
        @WebParam(name = "multiMovieYn", targetNamespace = "")
        String multiMovieYn,
        @WebParam(name = "repNationCd", targetNamespace = "")
        String repNationCd,
        @WebParam(name = "wideAreaCd", targetNamespace = "")
        String wideAreaCd)
        throws OpenAPIFault
    ;

    /**
     * 
     * @param multiMovieYn
     * @param wideAreaCd
     * @param repNationCd
     * @param itemPerPage
     * @param targetDt
     * @param key
     * @return
     *     returns wsdl.DailyBoxOfficeResult
     * @throws OpenAPIFault
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchDailyBoxOfficeList", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "wsdl.SearchDailyBoxOfficeList")
    @ResponseWrapper(localName = "searchDailyBoxOfficeListResponse", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "wsdl.SearchDailyBoxOfficeListResponse")
    public DailyBoxOfficeResult searchDailyBoxOfficeList(
        @WebParam(name = "key", targetNamespace = "")
        String key,
        @WebParam(name = "targetDt", targetNamespace = "")
        String targetDt,
        @WebParam(name = "itemPerPage", targetNamespace = "")
        String itemPerPage,
        @WebParam(name = "multiMovieYn", targetNamespace = "")
        String multiMovieYn,
        @WebParam(name = "repNationCd", targetNamespace = "")
        String repNationCd,
        @WebParam(name = "wideAreaCd", targetNamespace = "")
        String wideAreaCd)
        throws OpenAPIFault
    ;

}
