
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BoxOfficeAPIServiceImplService", targetNamespace = "http://service.boxoffice.server.apiservice.kobisopenapi/", wsdlLocation = "http://www.kobis.or.kr/kobisopenapi/webservice/soap/boxoffice?wsdl")
public class BoxOfficeAPIServiceImplService
    extends Service
{

    private final static URL BOXOFFICEAPISERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOXOFFICEAPISERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BOXOFFICEAPISERVICEIMPLSERVICE_QNAME = new QName("http://service.boxoffice.server.apiservice.kobisopenapi/", "BoxOfficeAPIServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.kobis.or.kr/kobisopenapi/webservice/soap/boxoffice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOXOFFICEAPISERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BOXOFFICEAPISERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BoxOfficeAPIServiceImplService() {
        super(__getWsdlLocation(), BOXOFFICEAPISERVICEIMPLSERVICE_QNAME);
    }

    public BoxOfficeAPIServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOXOFFICEAPISERVICEIMPLSERVICE_QNAME, features);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BOXOFFICEAPISERVICEIMPLSERVICE_QNAME);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOXOFFICEAPISERVICEIMPLSERVICE_QNAME, features);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BoxOfficeAPIService
     */
    @WebEndpoint(name = "BoxOfficeAPIServiceImplPort")
    public BoxOfficeAPIService getBoxOfficeAPIServiceImplPort() {
        return super.getPort(new QName("http://service.boxoffice.server.apiservice.kobisopenapi/", "BoxOfficeAPIServiceImplPort"), BoxOfficeAPIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoxOfficeAPIService
     */
    @WebEndpoint(name = "BoxOfficeAPIServiceImplPort")
    public BoxOfficeAPIService getBoxOfficeAPIServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.boxoffice.server.apiservice.kobisopenapi/", "BoxOfficeAPIServiceImplPort"), BoxOfficeAPIService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOXOFFICEAPISERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BOXOFFICEAPISERVICEIMPLSERVICE_EXCEPTION;
        }
        return BOXOFFICEAPISERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
