
package wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "OpenAPIFault", targetNamespace = "http://www.kobis.or.kr/kobisopenapi")
public class OpenAPIFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OpenApiFaultBean faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OpenAPIFault(String message, OpenApiFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public OpenAPIFault(String message, OpenApiFaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsdl.OpenApiFaultBean
     */
    public OpenApiFaultBean getFaultInfo() {
        return faultInfo;
    }

}
